
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      xcode_sdk: macosx10.10
      compiler: clang
      env: 
        - QT_BASE=55
        - QT_PREFIX_PATH="/usr/local/Cellar/qt@5.5/5.5.1_1/"
        - DEPLOYED_FILENAME="sargam.macosx10.10.zip"
        
#    - os: osx
#      osx_image: xcode8.3 # targetting sdk 10.12
#      xcode_sdk: macosx10.12
#      compiler: clang
#      env: 
#        - QT_BASE=59 
#        - QT_PREFIX_PATH="/usr/local/Cellar/qt/5.9.2/"
#        - DEPLOYED_FILENAME="sargam.macosx10.12.zip"

git:
  depth: 10

dist: trusty

before_install:
  - brew update


install:
  # install qt 5.5
  - if [ "$QT_BASE" = "55" ]; then
      travis_wait brew install qt55
    fi
  - if [ "$QT_BASE" = "59" ]; then
      travis_wait brew install qt5
    fi

script:
  - mkdir build
  - cd build

  cmake ../ -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH="$QT_PREFIX_PATH/lib/cmake/Qt5OpenGL;$QT_PREFIX_PATH/lib/cmake/Qt5Widgets;$QT_PREFIX_PATH/lib/cmake/Qt5PrintSupport;$QT_PREFIX_PATH/lib/cmake/Qt5Network"

  - cmake --build .

  
  #- /usr/local/Cellar/qt5/5.6.1-1/bin/macdeployqt ../bin/Sargam/Release/Sargam.app

before_deploy:
  #macdeployqt
  - $QT_PREFIX_PATH/bin/macdeployqt ../bin/Sargam/Release/Sargam.app
  - zip -r $DEPLOYED_FILENAME ../bin/Sargam/Release/Sargam.app
  - echo "deploying $DEPLOYED_FILENAME to GitHub releases"

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: 
    - $DEPLOYED_FILENAME
  on:
    tags: true

notifications:
  email: false

