
language: cpp

matrix:
  include:
#    - os: osx
#      osx_image: xcode6.4
#      xcode_sdk: macosx10.10
#      compiler: clang
#      env: 
#        - QT_BASE=55 QT_PREFIX_PATH="/usr/local/Cellar/qt@5.5/5.5.1_1/" DEPLOYED_FILENAME="sargam.macosx10.10.dmg"
        
    - os: osx
      osx_image: xcode8.3 # targetting sdk 10.12
      xcode_sdk: macosx10.12
      compiler: clang
      env: 
        - QT_BASE=59 QT_PREFIX_PATH="/usr/local/Cellar/qt/5.9.3/" DEPLOYED_FILENAME="sargam.macosx10.12.dmg"

git:
  depth: 10

dist: trusty

before_install:
  - brew update


install:
  # The 2 following lines are to install a specific version of
  # qt using a brew formula directly from a git commit in brew
  #
  # Qt 5.6.1-1
  #- travis_wait curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/fdfc724dd532345f5c6cdf47dc43e99654e6a5fd/Formula/qt5.rb
  #- travis_wait brew install ./qt5.rb

  # install qt 5.5
  - if [ "$QT_BASE" = "55" ]; then
      travis_wait brew install qt55;
    fi
  - if [ "$QT_BASE" = "59" ]; then
      travis_wait brew install qt5;
    fi

script:
  - mkdir build
  - cd build
  - cmake ../ -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH="$QT_PREFIX_PATH/lib/cmake/Qt5OpenGL;$QT_PREFIX_PATH/lib/cmake/Qt5Widgets;$QT_PREFIX_PATH/lib/cmake/Qt5PrintSupport;$QT_PREFIX_PATH/lib/cmake/Qt5Network"
  - cmake --build .

  
  #- /usr/local/Cellar/qt5/5.6.1-1/bin/macdeployqt ../bin/Sargam/Release/Sargam.app

before_deploy:
  #macdeployqt
  - $QT_PREFIX_PATH/bin/macdeployqt ../bin/Sargam/Release/Sargam.app -dmg
  - mv ../bin/Sargam/Release/Sargam.dmg "$DEPLOYED_FILENAME"
  - echo "deploying $DEPLOYED_FILENAME to GitHub releases"

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: 
    - "$DEPLOYED_FILENAME"
  on:
    tags: true

notifications:
  email: false

