
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      #xcode_sdk: macosx10.10
      compiler: clang
      env: 
        # - QT_BASE=59 
        #QT_59_PREFIX_PATH="/usr/local/Cellar/qt/5.9.2"
        $QT_56_PREFIX_PATH="/usr/local/opt/qt5/"

git:
  depth: 10

dist: trusty

before_install:
   - brew update
   #- sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y

install:
  #- travis_wait brew install qt55
  #- travis_wait brew link --force qt55;
  - travis_wait curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/fdfc724dd532345f5c6cdf47dc43e99654e6a5fd/Formula/qt5.rb
  - travis_wait brew install ./qt5.rb
  #- sudo apt-get install -qq qt56base;
  #- source /opt/qt56/bin/qt56-env.sh;

script:
  - mkdir build
  - cd build

  - pwd
  - ls

  - cmake ../ -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5/lib/cmake/Qt5OpenGL;/usr/local/opt/qt5/lib/cmake/Qt5Widgets;/usr/local/opt/qt5/lib/cmake/Qt5PrintSupport;/usr/local/opt/qt5/lib/cmake/Qt5Network"
  - cmake --build .

  #macdeployqt
  - /usr/local/opt/qt5/bin/macdeployqt ../bin/Sargam/Release/Sargam.app


notifications:
  email: false
