
language: none

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: CMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.9.1:$CMAKE_PREFIX_PATH

git:
  depth: 10

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi


script:
  - mkdir build
  - cd build
  - cmake ../ -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release"
  - cmake --build .


notifications:
  email: false
