
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: 
        # - QT_BASE=59 
        QT_PREFIX_PATH="/usr/local/Cellar/qt/5.9.2"

git:
  depth: 10

before_install:
   - brew update
   - travis_wait brew install qt5
   - travis_wait brew link --force qt5;


script:
  - mkdir build
  - cd build
  - cmake ../ -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH="/usr/local/Cellar/qt/5.9.2/clang_64/lib/cmake/Qt5OpenGL;/usr/local/Cellar/qt/5.9.2/clang_64/lib/cmake/Qt5Widgets;/usr/local/Cellar/qt/5.9.2/clang_64/lib/cmake/Qt5PrintSupport;/usr/local/Cellar/qt/5.9.2/clang_64/lib/cmake/Qt5Network"
  - cmake --build .


notifications:
  email: false
