
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env: 
        - QT_BASE=59

git:
  depth: 10

before_install:
   - brew update
   - brew install qt5
   - brew link --force qt5;


script:
  - mkdir build
  - cd build
  - cmake ../ -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release"
  - cmake --build .


notifications:
  email: false
